export const ENTER = "enter"
export const ENTERING = "entering"
export const ENTERED = "entered"
export const EXIT = "exit"
export const EXITING = "exiting"
export const EXITED = "exited"
export const UNMOUNTED = "unmounted"